# Generated by Django 4.1.10 on 2024-05-15 09:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('showDate', models.DateField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=30)),
                ('theaterName', models.CharField(max_length=70)),
                ('timing', models.TimeField()),
                ('totalSeats', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=300)])),
                ('availableSeats', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=300)])),
                ('occupiedSeats', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=300)])),
                ('ticketPrice', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_details_created', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.movie')),
            ],
        ),
    ]
